name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set mapbox token
      - name: Set Mapbox Token
        run: echo "MAPBOX_SECRET_TOKEN=${{ secrets.MAPBOX_SECRET_TOKEN }}" >> $GITHUB_ENV

      - name: Setup .netrc for Mapbox
        run: |
          echo "machine api.mapbox.com" > ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${{ secrets.MAPBOX_SECRET_TOKEN }}" >> ~/.netrc

      # Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0' 

      # Set up swift
      - name: Select Swift version
        run: sudo xcode-select --switch /Applications/Xcode_16.app

      # Resolve Swift Package dependencies
      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies

      # Build the app
      - name: Set IDESkipPackagePluginFingerprintValidatation
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Build the project
        run: xcodebuild -project CyBus.xcodeproj -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' -skipMacroValidation build

      # Run tests
      - name: Run tests
        run: xcodebuild test -project CyBus.xcodeproj -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' -skipMacroValidation
