name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: macos-15

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0.0'

      # Set mapbox token
      - name: Set Mapbox Token
        run: echo "MAPBOX_SECRET_TOKEN=${{ secrets.MAPBOX_SECRET_TOKEN }}" >> $GITHUB_ENV
    
      - name: Setup .netrc for Mapbox
        run: |
          echo "machine api.mapbox.com" > ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${{ secrets.MAPBOX_SECRET_TOKEN }}" >> ~/.netrc
    
      # Set mapbox token and other secrets
      - name: Create Config-Secret.xcconfig
        run: |
          echo "MBXAccessToken=${{ secrets.MAPBOX_SECRET_TOKEN }}" > CyBus/Config-Secret.xcconfig
          echo "GFTSServiceIP=20.19.98.194" >> CyBus/Config-Secret.xcconfig
          echo "GFTSServiceURL=$(GFTSServiceIP):8328/Api/api/gtfs-realtime" >> CyBus/Config-Secret.xcconfig

      # Set up swift
      # - name: Select Swift version
      #   run: sudo xcode-select --switch /Applications/Xcode.app

      # Clean Swift Package Manager dependencies
      # - name: Clean Swift Package Manager dependencies
      #   run: |
      #     rm -rf ~/Library/Developer/Xcode/DerivedData/*
      #     rm -rf CyBus.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
      #     rm -rf .build

      # Resolve Swift Package dependencies
      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test

      # Build the app
      # - name: Set IDESkipPackagePluginFingerprintValidatation
        # run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      # - name: Clean the project
      #   run: xcodebuild -project CyBus.xcodeproj -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' clean -quiet

      # - name: Build the project
        # run: xcodebuild -project CyBus.xcodeproj -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' build -quiet -skipMacroValidation

      # Run tests
      # - name: Run tests
      #   run: xcodebuild test -project CyBus.xcodeproj -scheme CyBus
