name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set mapbox token
      - name: Set Mapbox Token
        run: echo "MAPBOX_ACCESS_TOKEN=${{ secrets.MAPBOX_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Setup .netrc for Mapbox
        run: |
          echo "machine api.mapbox.com" > ~/.netrc
          echo "login mapbox" >> ~/.netrc
          echo "password ${{ secrets.MAPBOX_SECRET_ACCESS_TOKEN }}" >> ~/.netrc

      # Set up Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0' 

      # Resolve Swift Package dependencies
      - name: Resolve Swift Package dependencies
        run: xcodebuild -resolvePackageDependencies

      # Build the app
      - name: Build the project
        run: xcodebuild -workspace CyBus.xcworkspace -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' build

      # Run tests
      - name: Run tests
        run: xcodebuild test -workspace CyBus.xcworkspace -scheme CyBus -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16'
